### PR TITLE
add ability to find models with tags of any type

### PR DESCRIPTION
**Pull request by mokhosh**
This adds two new scopes:
```php
scopeWithAllTagsOfAnyType
scopeWithAnyTagsOfAnyType
```

and to be clean about it, I added one method to `HasTags` trait and another to the `Tag` model to convert given arguments to tags of any type and find tags of any type from strings:
```php
HasTags::convertToTagsOfAnyType
Tag::findFromStringOfAnyType
```

I also added `.idea` folder to gitignore :)

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you for this. 👍  Could you add tests to make sure that this works?

I've remove the  `.idea` again, because this belongs in a global `.gitignore`.

**Comment by freekmurze** [comment]
Travis reports that the `t_provides_as_scope_to_get_all_models_that_have_any_of_the_given_tags_with_type` is not running properly.  https://travis-ci.org/spatie/laravel-tags/jobs/469729909

Could you take a look at that?

> it says unknown database laravel-tags although I have created this database and I have created a .env file with mysql credentials.
That's something specific to your system, can't help you with that I'm afraid.

> I don't know how to run migrations without artisan.
Running the tests will run the migrations

> I also had to use php vendor\phpunit\phpunit\phpunit tests instead of just phpunit tests which doesn't seem right
That's normal, I'll update the readme

> don't start throwing tomatos 
Never, you're safe here 😄 

> it's my first time doing a pull request
👍

**Comment by mokhosh** [comment]
> Travis reports that the t_provides_as_scope_to_get_all_models_that_have_any_of_the_given_tags_with_type is not running properly. https://travis-ci.org/spatie/laravel-tags/jobs/469729909

It was one of the original tests that stopped working because I added `model6`. Fixed it.

> That's something specific to your system, can't help you with that I'm afraid.

It was a very sophisticated problem related to using a `-` instead of a `_` for db name 😄 

Thanks for being welcoming. I guess this is ready.

**Comment by mokhosh** [comment]
> Thank you very much for your work on this! 👍

Well, thank you for all your great packages! 👍 

> @mokhosh are you up for sending a PR to the docs for these two new scopes?

Sure, it's been fun. Also, there's a Farsi proverb that says "Do you know who did the job? The one who made it complete." 😄

**Comment by mokhosh** [comment]
Done https://github.com/spatie/docs.spatie.be/pull/374

**Pull request merged**
