### PR TITLE
Return slugs in find methods

### PR DESCRIPTION
**Pull request by falconsmilie**
https://github.com/spatie/laravel-tags/discussions/437

I assume if a "name" is in slug format, that the slug will be the same as the name?!

Assumption aside, I don't see any side effects for methods like `findOrCreateFromString` which call these changed functions.

### CODE REVIEW

**Comment by freekmurze** [comment]
The tests are failing for this one, could you take a look?

**Comment by falconsmilie** [comment]
i get the same fails locally when running the test _without_ any changes. I tried to trigger the tests again here, but seems they were skipped with no diff.

**Comment by freekmurze** [comment]
I've fixed the tests on `main`. Could you rebase this PR?

**Comment by falconsmilie** [comment]
I've pushed some changes, all tests pass locally.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
