### PR TITLE
Added ability to specify a different connection for the tags and taggables tables

### PR DESCRIPTION
**Pull request by vesper8**
In many of my projects I use multiple database connections and this minor modification is required in order to make things work with this package.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for this PR. I'm not going to merge it because the vast majority of users probably doesn't need this feature. You can add the `getConnectionName` to your own models in your own project.

**Comment by semprul57** [comment]
> Thanks for this PR. I'm not going to merge it because the vast majority of users probably doesn't need this feature. You can add the `getConnectionName` to your own models in your own project.

So to automatically detect the connection i should override laravel model method like this : 
```
class Universe extends Model {
     use \Spatie\Tags\HasTags;

     protected $connection = "universe_db";
     .......
     .......
     public function getConnectionName()
     {
          return $this->connection;
     }
}
```

is that correct? because my model still can't identify the connection.

**Comment by vesper8** [comment]
@semprul57 The only way I've been able to get this to work is by creating a trait of my own called HasTags and copying the contents of the HasTags from this package and then adding the `getConnectionName()` method to that trait which should return the custom connection you want to use for your tags and taggables.

This is the only way because you cannot extend a trait. Alternatively you can create a fork and add the method there.

**Comment by semprul57** [comment]
@vesper8 from your pull request i see that you set the database from config file, what i try to approach is to get dynamic connection based on parent model, so if i call `a_model` and try to insert the tags it will automatically insert to `a_database` and so on.

**Comment by vesper8** [comment]
That should not be a problem. Since the getConnectionName is normally in the trait, that means it is just another method added to the model that uses tags. So you could add the method directly on your model instead of inside the trait. I am adding it to the trait since all my models have traits on the same database.

However if you have multiple connections that all use tags.. then you'll have to worry about making sure that your migrations create the tags table on multiple connections as well

**Comment by semprul57** [comment]
@vesper8 it doesn't work and can't get the default connection from the model that uses tags, the tags only inserted to default database connection.
That's why i reply this issue and try to figure out to insert tags based on `$connection` in model

**Pull request closed without merging**
