### PR TITLE
Fix the tests

### PR DESCRIPTION
**Pull request by SelimSalihovic**

### CODE REVIEW

**Comment by freekmurze** [comment]
Just wanted to say that, regardless of the outcome, I highly appreciate your help on fixing the tests.

**Comment by SelimSalihovic** [comment]
Seems like this fixes the tests but I have temporarily disabled `HasTagsTest::it_can_sync_tags_with_different_types` because this method fails when the test suite is ran with the --prefer-lowest flag.

I'm currently looking into what package (and what exact version) is causing this. After that is fixed we can have HasTagsTest run on CI again.

**Comment by freekmurze** [comment]
Thank you very much for this 👍

**Comment by freekmurze** [comment]
Seems like there's still one strange thing going on. No tests are executed when using PHP 7.1 with the lower requirements. Example: https://travis-ci.org/spatie/laravel-tags/jobs/244072893

**Pull request merged**
