### PR TITLE
add deleted event to detach tags on model delete

### PR DESCRIPTION
**Pull request by fetzi**
This PR detaches all tags from the model as mentioned in #44.

The solution will not work for mass deletes because the deleted Event won't get fired.

Maybe a cleanup command would be a solution, @freekmurze what do you think?

### CODE REVIEW

**Comment by fetzi** [comment]
@freekmurze Tests fail because of `The command "sudo apt-get install mysql-server-5.7" failed and exited with 100 during .`

**Comment by freekmurze** [comment]
> Maybe a cleanup command

Yup, could you add a fully tested cleanup command to the package? Maybe to that in a seperate PR (if you feel up to it).

> Tests fail because of The command "sudo apt-get install mysql-server-5.7" failed and exited with 100 during .

If you have the time, go through the Travis docs to learn how that may be fixed. Otherwise I'll take a look at this problem when I have a bit of time on my hands.

**Comment by freekmurze** [comment]
Could you try chaging `mysql-server-5.7` to `mysql-server` to see if that helps?

**Comment by freekmurze** [comment]
The tests have been fixed in the `master` branch. Could you rebase that PR against the current version in `master`?

**Comment by fetzi** [comment]
@freekmurze I've merged master but tests continue to fail.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
