### PR TITLE
change phpunit to pest testing framework

### PR DESCRIPTION
**Pull request by uthadehikaru**
Hi,

i got the challenge from [@freekmurze](https://twitter.com/freekmurze) tweet about converting spatie package unit test from phpunit to pest.

i'm new in unit testing and pest is really impressive me with the simplicity. i tried my best and the test is passed all without any change on scenario.

maybe i will try to scan all spatie package to change unit test from phpunit to pest. :D

thanks for the chance

### CODE REVIEW

**Review by freekmurze — CHANGES_REQUESTED** [review]
Thank you, could you also convert all assertions to the expectations?
https://pestphp.com/docs/expectations

**Comment by freekmurze** [comment]
Also add [this section](https://github.com/spatie/laravel-model-flags/blob/a939c25086e75e2268fb5511cefddb90a044d560/composer.json#L51-L53) to composer.json to make the tests run on GitHub actions.

**Comment by uthadehikaru** [comment]
bug fix when run composer on github action

**Comment by uthadehikaru** [comment]
i changed assertions to the expectations. i'm wondering that expectations on pestphp just like Str helper as advance php string functions on laravel.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
